#!/bin/bash

docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/latex resume.md -o resume.pdf \
	-f markdown+smart \
	--standalone \
	--email-obfuscation=references \
	--variable="pagetitle:Resume :: Erin Burton"
